In [1]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .appName("S3 Parquet Analysis")
    .getOrCreate()
)

spark

26/01/23 14:12:24 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [2]:
import sys
sys.path.append("/opt/lakehouse/lakehouse")

from lakehouse.paths import PathResolver

resolver = PathResolver()

In [3]:
s3_bronze_path_Contrat2 = resolver.s3_layer_path(
    layer="bronze",
    dataset="Contrat2"
)

In [4]:
df = spark.read.parquet(s3_bronze_path_Contrat2)

df.printSchema()
df.show(5)

26/01/23 14:12:25 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties

root
 |-- nusoc: integer (nullable = true)
 |-- nucon: integer (nullable = true)
 |-- cateco: string (nullable = true)
 |-- g01co: integer (nullable = true)
 |-- g02co: integer (nullable = true)
 |-- g03co: integer (nullable = true)
 |-- g04co: integer (nullable = true)
 |-- g05co: integer (nullable = true)
 |-- g06co: integer (nullable = true)
 |-- g09co: integer (nullable = true)
 |-- g10co: integer (nullable = true)
 |-- g13co: integer (nullable = true)
 |-- g15co: integer (nullable = true)
 |-- g16co: integer (nullable = true)
 |-- g17co: integer (nullable = true)
 |-- g18co: integer (nullable = true)
 |-- g19co: integer (nullable = true)
 |-- g21co: integer (nullable = true)
 |-- g22co: integer (nullable = true)
 |-- g23co: integer (nullable = true)
 |-- g25co: integer (nullable = true)
 |-- g26co: integer (nullable = true)
 |-- g28co: integer (nullable = true)
 |-- clasco: string (nullable = true)
 |-- tar6co: string (nullable = true)
 |-- bomaco: double (nullable = true)
 |-- fracco: string (nullable = true)
 |-- famgta: string (nullable = true)
 |-- markli: string (nullable = true)
 |-- apcoco: string (nullable = true)
 |-- acircu: integer (nullable = true)
 |-- mcircu: integer (nullable = true)
 |-- acreco: integer (nullable = true)
 |-- mcreco: integer (nullable = true)
 |-- jcreco: integer (nullable = true)
 |-- prmaco: double (nullable = true)
 |-- etatco: string (nullable = true)
 |-- asaico: integer (nullable = true)
 |-- msaico: integer (nullable = true)
 |-- jsaico: integer (nullable = true)
 |-- utimot: string (nullable = true)
 |-- pfco: integer (nullable = true)
 |-- usagco1: integer (nullable = true)

26/01/23 14:12:31 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+------+-----+------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+-----------------+----------+--------------------+------+------+------+------+------+------+------+------+------+------+------+----+-------+
| nusoc|nucon|cateco|g01co|g02co|g03co|g04co|g05co|g06co|g09co|g10co|g13co|g15co|g16co|g17co|g18co|g19co|g21co|g22co|g23co|g25co|g26co|g28co|clasco|tar6co|bomaco|fracco|           famgta|    markli|              apcoco|acircu|mcircu|acreco|mcreco|jcreco|prmaco|etatco|asaico|msaico|jsaico|utimot|pfco|usagco1|
+------+-----+------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+-----------------+----------+--------------------+------+------+------+------+------+------+------+------+------+------+------+----+-------+
|386899|    1|     M|    1|    1|    1|    1|    1|    1|    1|    0|    1|    0|    0|    1|    0|    0|    1|    0|    0|    0|    1|    0|     4|  NULL|  0.76|     S|             0750|  KAWASAKI|          Z 750-N IE|  2006|     5|  2003|     3|     1|699.84|     3|  2008|     4|    16|    SB|   7|      0|
|386899|    2|     A|    1|    1|    1|    1|    1|    1|    1|    0|    0|    0|    0|    1|    0|    1|    1|    0|    0|    0|    0|    0|     6|  NULL|   0.6|     S|             POLO|VOLKSWAGEN|          1.4 TDI 70|  2007|    11|  2004|     7|     1| 782.2|     3|  2010|     6|    23|  NULL|   4|      0|
|386899|    3|     A|    1|    1|    1|    1|    1|    1|    1|    0|    0|    0|    0|    1|    0|    1|    1|    0|    0|    0|    0|    0|     6|  NULL|   0.6|     S|               C3|   CITROEN|1.4 HDI 70 GENERATIO|  2006|    12|  2010|     6|    18|650.97|     3|  2011|     4|    17|  NULL|   6|      0|
|386899|    4|     A|    1|    1|    1|    1|    1|    1|    1|    0|    0|    0|    0|    1|    0|    1|    1|    0|    0|    0|    0|    0|     6|  NULL|   0.6|     S|              207|   PEUGEOT|   1.4 HDI 70 TRENDY|  2006|    10|  2011|     8|    27|643.52|     3|  2012|     2|    28|  NULL|   4|      0|
|386902|    1|     M|    1|    1|    1|    1|    1|    1|    1|    0|    1|    0|    0|    1|    0|    0|    1|    0|    0|    0|    0|    0|     4|     N|   0.5|     A|06500000000000000|     HONDA|           DEAUVILLE|  1999|     9|  2003|     2|    28|525.89|     3|  2005|     2|    16|    GT|   7|      0|
+------+-----+------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+-----------------+----------+--------------------+------+------+------+------+------+------+------+------+------+------+------+----+-------+
only showing top 5 rows

In [5]:
s3_bronze_path_contrat1 = resolver.s3_layer_path(
    layer="bronze",
    dataset="contrat1"
)

In [6]:
df1 = spark.read.parquet(s3_bronze_path_contrat1)

df1.printSchema()
df1.show(5)

root
 |-- nusoc: integer (nullable = true)
 |-- nucon: integer (nullable = true)
 |-- cateco: string (nullable = true)
 |-- g01co: integer (nullable = true)
 |-- g02co: integer (nullable = true)
 |-- g03co: integer (nullable = true)
 |-- g04co: integer (nullable = true)
 |-- g05co: integer (nullable = true)
 |-- g06co: integer (nullable = true)
 |-- g09co: integer (nullable = true)
 |-- g10co: integer (nullable = true)
 |-- g13co: integer (nullable = true)
 |-- g15co: integer (nullable = true)
 |-- g16co: integer (nullable = true)
 |-- g17co: integer (nullable = true)
 |-- g18co: integer (nullable = true)
 |-- g19co: integer (nullable = true)
 |-- g21co: integer (nullable = true)
 |-- g22co: integer (nullable = true)
 |-- g23co: integer (nullable = true)
 |-- g25co: integer (nullable = true)
 |-- g26co: integer (nullable = true)
 |-- g28co: integer (nullable = true)
 |-- clasco: string (nullable = true)
 |-- tar6co: string (nullable = true)
 |-- bomaco: double (nullable = true)
 |-- fracco: string (nullable = true)
 |-- famgta: string (nullable = true)
 |-- markli: string (nullable = true)
 |-- apcoco: string (nullable = true)
 |-- acircu: integer (nullable = true)
 |-- mcircu: integer (nullable = true)
 |-- acreco: integer (nullable = true)
 |-- mcreco: integer (nullable = true)
 |-- jcreco: integer (nullable = true)
 |-- prmaco: double (nullable = true)
 |-- etatco: string (nullable = true)
 |-- asaico: integer (nullable = true)
 |-- msaico: integer (nullable = true)
 |-- jsaico: integer (nullable = true)
 |-- utimot: string (nullable = true)
 |-- pfco: integer (nullable = true)
 |-- usagco1: integer (nullable = true)

+-----+-----+------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+------+------+------+------+------+------+------+------+-------+------+------+------+------+------+----+-------+
|nusoc|nucon|cateco|g01co|g02co|g03co|g04co|g05co|g06co|g09co|g10co|g13co|g15co|g16co|g17co|g18co|g19co|g21co|g22co|g23co|g25co|g26co|g28co|clasco|tar6co|bomaco|fracco|famgta|markli|apcoco|acircu|mcircu|acreco|mcreco|jcreco| prmaco|etatco|asaico|msaico|jsaico|utimot|pfco|usagco1|
+-----+-----+------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+------+------+------+------+------+------+------+------+-------+------+------+------+------+------+----+-------+
|    1|    2|     A|    1|    1|    1|    0|    1|    1|    0|    0|    0|    0|    0|    0|    0|    0|    1|    0|    0|    0|    0|    0|     5|  NULL|   0.5|     A|  1300|POLSKI|1300PX|  1984|     5|  1984|     5|     9|  324.5|     9|  1987|    12|    23|     R|   7|      0|
|    1|    1|     M|    1|    1|    1|    0|    1|    0|    0|    0|    0|    0|    0|    0|    0|    0|    1|    0|    0|    0|    0|    0|     5|  NULL|  0.55|     A|  1000|   BMW|R100TC|  1983|     7|  1984|     1|    19| 509.89|     3|  1987|    12|    23|     R|   9|      0|
|    3|    1|     M|    1|    1|    1|    1|    1|    1|    1|    0|    1|    0|    0|    1|    0|    0|    1|    0|    0|    0|    0|    0|     6|  NULL|   0.5|     A|  0600|SUZUKI|   GSR|  2006|    10|  1995|     3|    18| 739.54|     3|  2007|     2|     1|    SB|   6|      0|
|    5|    1|     M|    1|    1|    1|    0|    1|    0|    0|    0|    0|    0|    0|    0|    0|    0|    1|    0|    0|    0|    0|    0|     3|  NULL|   1.0|     A|  0500|SUZUKI|RG500G|  1986|    10|  1986|     9|    30|1366.44|     4|  1987|    12|    23|    SS|   5|      0|
|    8|    1|     M|    1|    1|    1|    0|    1|    0|    0|    0|    0|    0|    0|    0|    0|    0|    1|    0|    0|    0|    0|    0|     1|  NULL|   1.0|     A|  0500| GUZZI|  NULL|  1981|     6|  1983|     9|    20|1260.05|     3|  1987|    12|    23|     R|   5|      0|
+-----+-----+------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+------+------+------+------+------+------+------+------+-------+------+------+------+------+------+----+-------+
only showing top 5 rows

In [7]:
df_pd=df.toPandas()
df_pd

,nusoc,nucon,cateco,g01co,g02co,g03co,g04co,g05co,g06co,g09co,...,mcreco,jcreco,prmaco,etatco,asaico,msaico,jsaico,utimot,pfco,usagco1
0,386899,1,M,1,1,1,1,1,1,1,...,3,1,699.84,3,2008,4,16,SB,7,0
1,386899,2,A,1,1,1,1,1,1,1,...,7,1,782.20,3,2010,6,23,None,4,0
2,386899,3,A,1,1,1,1,1,1,1,...,6,18,650.97,3,2011,4,17,None,6,0
3,386899,4,A,1,1,1,1,1,1,1,...,8,27,643.52,3,2012,2,28,None,4,0
4,386902,1,M,1,1,1,1,1,1,1,...,2,28,525.89,3,2005,2,16,GT,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70609,421616,2,M,1,1,1,1,1,0,0,...,11,6,150.30,1,2022,3,31,TR,1,0
70610,421616,1,M,1,1,1,1,1,0,0,...,3,5,131.73,1,2022,3,31,TR,4,0
70611,421617,1,M,1,1,0,0,0,0,0,...,3,5,229.10,3,2010,1,14,B,7,0
70612,421618,5,M,1,1,0,0,0,0,0,...,9,23,219.01,3,2017,2,13,SCB,1,0
70613,421618,4,M,1,1,0,0,0,0,0,...,6,3,61.74,1,2022,5,24,TR,3,0

In [8]:
df1_pd=df1.toPandas()
df1_pd

,nusoc,nucon,cateco,g01co,g02co,g03co,g04co,g05co,g06co,g09co,...,mcreco,jcreco,prmaco,etatco,asaico,msaico,jsaico,utimot,pfco,usagco1
0,1,2,A,1,1,1,0,1,1,0,...,5,9,324.50,9,1987,12,23,R,7,0
1,1,1,M,1,1,1,0,1,0,0,...,1,19,509.89,3,1987,12,23,R,9,0
2,3,1,M,1,1,1,1,1,1,1,...,3,18,739.54,3,2007,2,1,SB,6,0
3,5,1,M,1,1,1,0,1,0,0,...,9,30,1366.44,4,1987,12,23,SS,5,0
4,8,1,M,1,1,1,0,1,0,0,...,9,20,1260.05,3,1987,12,23,R,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,146537,3,A,1,1,0,0,0,0,0,...,3,31,370.37,3,2000,2,2,None,7,0
99996,146538,1,M,1,1,0,0,0,0,0,...,8,18,127.52,3,2008,2,18,CU,6,0
99997,146540,3,C,1,1,0,0,0,0,0,...,8,3,217.09,3,2004,2,12,SS,0,0
99998,146540,5,C,1,1,0,0,0,0,0,...,4,7,265.65,3,2005,1,28,SS,0,0
99999,146540,1,M,1,1,1,1,1,1,1,...,8,18,411.55,3,2009,3,23,CU,13,0

In [9]:
df_pd.shape

(70614, 43)

In [10]:
df1_pd.shape

(100000, 43)

Concatiner les 2 dataset Contrat1 et contrat 2

In [11]:
df_conc = df.unionByName(df1)

In [12]:
df_conc_pd=df_conc.toPandas()
df_conc_pd

,nusoc,nucon,cateco,g01co,g02co,g03co,g04co,g05co,g06co,g09co,...,mcreco,jcreco,prmaco,etatco,asaico,msaico,jsaico,utimot,pfco,usagco1
0,386899,1,M,1,1,1,1,1,1,1,...,3,1,699.84,3,2008,4,16,SB,7,0
1,386899,2,A,1,1,1,1,1,1,1,...,7,1,782.20,3,2010,6,23,None,4,0
2,386899,3,A,1,1,1,1,1,1,1,...,6,18,650.97,3,2011,4,17,None,6,0
3,386899,4,A,1,1,1,1,1,1,1,...,8,27,643.52,3,2012,2,28,None,4,0
4,386902,1,M,1,1,1,1,1,1,1,...,2,28,525.89,3,2005,2,16,GT,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170609,146537,3,A,1,1,0,0,0,0,0,...,3,31,370.37,3,2000,2,2,None,7,0
170610,146538,1,M,1,1,0,0,0,0,0,...,8,18,127.52,3,2008,2,18,CU,6,0
170611,146540,3,C,1,1,0,0,0,0,0,...,8,3,217.09,3,2004,2,12,SS,0,0
170612,146540,5,C,1,1,0,0,0,0,0,...,4,7,265.65,3,2005,1,28,SS,0,0
170613,146540,1,M,1,1,1,1,1,1,1,...,8,18,411.55,3,2009,3,23,CU,13,0

A. Normalisation des types

In [13]:
from pyspark.sql.functions import col, when

df_silver = df_conc  \
    .withColumn("nusoc", col("nusoc").cast("int")) \
    .withColumn("nucon", col("nucon").cast("int")) \
    .withColumn("prmaco", col("prmaco").cast("double")) \
    .withColumn("pfco", col("pfco").cast("int")) \
    .withColumn("asaico", col("asaico").cast("int"))

In [14]:
df_silver_pd=df_silver.toPandas()
df_silver_pd

,nusoc,nucon,cateco,g01co,g02co,g03co,g04co,g05co,g06co,g09co,...,mcreco,jcreco,prmaco,etatco,asaico,msaico,jsaico,utimot,pfco,usagco1
0,386899,1,M,1,1,1,1,1,1,1,...,3,1,699.84,3,2008,4,16,SB,7,0
1,386899,2,A,1,1,1,1,1,1,1,...,7,1,782.20,3,2010,6,23,None,4,0
2,386899,3,A,1,1,1,1,1,1,1,...,6,18,650.97,3,2011,4,17,None,6,0
3,386899,4,A,1,1,1,1,1,1,1,...,8,27,643.52,3,2012,2,28,None,4,0
4,386902,1,M,1,1,1,1,1,1,1,...,2,28,525.89,3,2005,2,16,GT,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170609,146537,3,A,1,1,0,0,0,0,0,...,3,31,370.37,3,2000,2,2,None,7,0
170610,146538,1,M,1,1,0,0,0,0,0,...,8,18,127.52,3,2008,2,18,CU,6,0
170611,146540,3,C,1,1,0,0,0,0,0,...,8,3,217.09,3,2004,2,12,SS,0,0
170612,146540,5,C,1,1,0,0,0,0,0,...,4,7,265.65,3,2005,1,28,SS,0,0
170613,146540,1,M,1,1,1,1,1,1,1,...,8,18,411.55,3,2009,3,23,CU,13,0

B. Gestion des valeurs manquantes

In [15]:
from pyspark.sql.functions import when

df_silver = df_silver \
    .withColumn("pfco", when(col("pfco").isNull(), 0).otherwise(col("pfco"))) \
    .withColumn("etatco", when(col("etatco").isNull(), "UNKNOWN").otherwise(col("etatco"))) \
    .withColumn("prmaco", when(col("prmaco").isNull(), 0.0).otherwise(col("prmaco")))

C. Suppression des doublons contrat

In [16]:
df_silver = df_silver.dropDuplicates(["nusoc", "nucon"])

In [17]:
df_silver_pd=df_silver.toPandas()
df_silver_pd

,nusoc,nucon,cateco,g01co,g02co,g03co,g04co,g05co,g06co,g09co,...,mcreco,jcreco,prmaco,etatco,asaico,msaico,jsaico,utimot,pfco,usagco1
0,3,1,M,1,1,1,1,1,1,1,...,3,18,739.54,3,2007,2,1,SB,6,0
1,15,14,M,1,1,1,1,1,1,1,...,11,16,285.60,1,2022,3,31,SCB,1,0
2,15,15,M,1,1,1,1,1,1,1,...,12,7,234.81,1,2022,3,31,SGR,1,0
3,16,3,A,1,1,1,1,1,1,1,...,3,9,657.90,1,2022,3,31,None,7,0
4,18,1,M,1,1,1,1,1,1,1,...,7,17,2107.68,0,2013,7,16,SCS,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170609,421533,1,A,1,1,0,0,0,0,0,...,3,5,412.65,3,2014,1,14,None,6,0
170610,421538,1,M,1,1,0,0,0,0,0,...,3,3,221.92,3,2017,3,21,BS,6,0
170611,421571,1,M,1,1,0,0,0,0,0,...,2,27,113.01,4,2016,7,29,T,1,0
170612,421588,4,M,1,1,1,1,1,1,1,...,5,3,253.03,1,2022,3,31,CU,8,0
170613,421608,2,M,1,1,0,0,0,0,0,...,12,31,325.76,3,2021,6,28,SS,9,0

3 - Transformations SILVER MÉTIER

D. Décodage des variables métier

In [18]:
#Type de vehicule
from pyspark.sql.functions import when

df_silver = df_silver.withColumn(
    "type_vehicule",
    when(col("cateco") == "A", "Auto")
    .when(col("cateco") == "M", "Moto")
    .when(col("cateco") == "C", "Cyclo")
    .otherwise("Inconnu")
)

In [34]:
#etat de contart
df_silver = df_silver.withColumn(
    "etat_contrat_libelle",
    when(col("etatco") == "0", "Annulé")
    .when(col("etatco") == "1", "En cours")
    .when(col("etatco") == "2", "Suspendu")
    .when(col("etatco") == "3", "Résilié sociétaire") 
    .when(col("etatco") == "4", "Résilié impayé") 
    .when(col("etatco") == "7", " Résilié article 25 (hausse tarifaire)") 
    .when(col("etatco") == "9", " Résilié Mutuelle") 
    
    .otherwise("Autre")
)

In [20]:
#Usage du véhicule
df_silver = df_silver.withColumn(
    "usage_vehicule",
    when(col("usagco1") == 0, "Domicile-Travail")
    .when(col("usagco1") == 1, "Promenade")
    .when(col("usagco1") == 3, "Professionnel")
    .otherwise("Autre")
)

In [35]:
df_silver_pd=df_silver.toPandas()
df_silver_pd

,nusoc,nucon,cateco,g01co,g02co,g03co,g04co,g05co,g06co,g09co,...,msaico,jsaico,utimot,pfco,usagco1,type_vehicule,etat_contrat_libelle,usage_vehicule,nb_garanties,anciennete_contrat
0,3,1,M,1,1,1,1,1,1,1,...,2,1,SB,6,0,Moto,Résilié sociétaire,Domicile-Travail,10,19
1,15,14,M,1,1,1,1,1,1,1,...,3,31,SCB,1,0,Moto,En cours,Domicile-Travail,11,4
2,15,15,M,1,1,1,1,1,1,1,...,3,31,SGR,1,0,Moto,En cours,Domicile-Travail,11,4
3,16,3,A,1,1,1,1,1,1,1,...,3,31,None,7,0,Auto,En cours,Domicile-Travail,10,4
4,18,1,M,1,1,1,1,1,1,1,...,7,16,SCS,6,0,Moto,Annulé,Domicile-Travail,11,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170609,421533,1,A,1,1,0,0,0,0,0,...,1,14,None,6,0,Auto,Résilié sociétaire,Domicile-Travail,4,12
170610,421538,1,M,1,1,0,0,0,0,0,...,3,21,BS,6,0,Moto,Résilié sociétaire,Domicile-Travail,6,9
170611,421571,1,M,1,1,0,0,0,0,0,...,7,29,T,1,0,Moto,Résilié impayé,Domicile-Travail,5,10
170612,421588,4,M,1,1,1,1,1,1,1,...,3,31,CU,8,0,Moto,En cours,Domicile-Travail,11,4
170613,421608,2,M,1,1,0,0,0,0,0,...,6,28,SS,9,0,Moto,Résilié sociétaire,Domicile-Travail,5,5

E. Regroupement des garanties

Au lieu de 20 colonnes gXXco, on crée des indicateurs synthétiques.

In [22]:
from pyspark.sql.functions import expr

garanties = [
    "g01co","g02co","g03co","g04co","g05co","g06co","g09co",
    "g10co","g13co","g15co","g16co","g17co","g18co","g19co",
    "g21co","g22co","g23co","g25co","g26co","g28co"
]

df_silver = df_silver.withColumn(
    "nb_garanties",
    sum(col(g) for g in garanties)
)

In [23]:
df_silver_pd=df_silver.toPandas()
df_silver_pd

,nusoc,nucon,cateco,g01co,g02co,g03co,g04co,g05co,g06co,g09co,...,asaico,msaico,jsaico,utimot,pfco,usagco1,type_vehicule,etat_contrat_libelle,usage_vehicule,nb_garanties
0,3,1,M,1,1,1,1,1,1,1,...,2007,2,1,SB,6,0,Moto,Autre,Domicile-Travail,10
1,15,14,M,1,1,1,1,1,1,1,...,2022,3,31,SCB,1,0,Moto,En cours,Domicile-Travail,11
2,15,15,M,1,1,1,1,1,1,1,...,2022,3,31,SGR,1,0,Moto,En cours,Domicile-Travail,11
3,16,3,A,1,1,1,1,1,1,1,...,2022,3,31,None,7,0,Auto,En cours,Domicile-Travail,10
4,18,1,M,1,1,1,1,1,1,1,...,2013,7,16,SCS,6,0,Moto,Annulé,Domicile-Travail,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170609,421533,1,A,1,1,0,0,0,0,0,...,2014,1,14,None,6,0,Auto,Autre,Domicile-Travail,4
170610,421538,1,M,1,1,0,0,0,0,0,...,2017,3,21,BS,6,0,Moto,Autre,Domicile-Travail,6
170611,421571,1,M,1,1,0,0,0,0,0,...,2016,7,29,T,1,0,Moto,Autre,Domicile-Travail,5
170612,421588,4,M,1,1,1,1,1,1,1,...,2022,3,31,CU,8,0,Moto,En cours,Domicile-Travail,11
170613,421608,2,M,1,1,0,0,0,0,0,...,2021,6,28,SS,9,0,Moto,Autre,Domicile-Travail,5

In [36]:
df_silver.groupBy("etat_contrat_libelle").count().show()

+--------------------+------+
|etat_contrat_libelle| count|
+--------------------+------+
|    Résilié Mutuelle|  4346|
|            En cours| 19859|
|      Résilié impayé| 10242|
| Résilié article ...|  1546|
|            Suspendu|   268|
|  Résilié sociétaire|132351|
|              Annulé|  2002|
+--------------------+------+

F. Création de variables analytiques clés

In [24]:
df_silver = df_silver.withColumnRenamed(
    "asaico", "annee_souscription"
)

In [25]:
df_silver_pd=df_silver.toPandas()
df_silver_pd

,nusoc,nucon,cateco,g01co,g02co,g03co,g04co,g05co,g06co,g09co,...,annee_souscription,msaico,jsaico,utimot,pfco,usagco1,type_vehicule,etat_contrat_libelle,usage_vehicule,nb_garanties
0,3,1,M,1,1,1,1,1,1,1,...,2007,2,1,SB,6,0,Moto,Autre,Domicile-Travail,10
1,15,14,M,1,1,1,1,1,1,1,...,2022,3,31,SCB,1,0,Moto,En cours,Domicile-Travail,11
2,15,15,M,1,1,1,1,1,1,1,...,2022,3,31,SGR,1,0,Moto,En cours,Domicile-Travail,11
3,16,3,A,1,1,1,1,1,1,1,...,2022,3,31,None,7,0,Auto,En cours,Domicile-Travail,10
4,18,1,M,1,1,1,1,1,1,1,...,2013,7,16,SCS,6,0,Moto,Annulé,Domicile-Travail,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170609,421533,1,A,1,1,0,0,0,0,0,...,2014,1,14,None,6,0,Auto,Autre,Domicile-Travail,4
170610,421538,1,M,1,1,0,0,0,0,0,...,2017,3,21,BS,6,0,Moto,Autre,Domicile-Travail,6
170611,421571,1,M,1,1,0,0,0,0,0,...,2016,7,29,T,1,0,Moto,Autre,Domicile-Travail,5
170612,421588,4,M,1,1,1,1,1,1,1,...,2022,3,31,CU,8,0,Moto,En cours,Domicile-Travail,11
170613,421608,2,M,1,1,0,0,0,0,0,...,2021,6,28,SS,9,0,Moto,Autre,Domicile-Travail,5

Segment Anciente

In [26]:
from pyspark.sql.functions import lit, col, year, current_date

df_silver = df_silver.withColumn(
    "anciennete_contrat",
    year(current_date()) - col("annee_souscription")
)

In [ ]:
df_silver_pd=df_silver.toPandas()
df_silver_pd

Table Client

In [41]:
s3_bronze_path_client = resolver.s3_layer_path(
    layer="bronze",
    dataset="Client"
)

In [42]:
df_c = spark.read.parquet(s3_bronze_path_client)

df_c.printSchema()
df_c.show(5)

root
 |-- nusoc: integer (nullable = true)
 |-- cdepso: string (nullable = true)
 |-- cvilso: string (nullable = true)
 |-- sexsoc: string (nullable = true)
 |-- bgesso: string (nullable = true)
 |-- aadhso: integer (nullable = true)
 |-- anaiso: integer (nullable = true)
 |-- mnaiso: integer (nullable = true)
 |-- jnaiso: integer (nullable = true)
 |-- cspsoc: string (nullable = true)
 |-- asaiso: string (nullable = true)
 |-- msaico: integer (nullable = true)
 |-- jsaiso: integer (nullable = true)
 |-- sitmat: string (nullable = true)
 |-- nbenf: integer (nullable = true)
 |-- accmai: string (nullable = true)
 |-- accsms: string (nullable = true)
 |-- sitpav1: string (nullable = true)

+-----+------+------+------+------+------+------+------+------+------+------+------+------+------+-----+------+------+----------+
|nusoc|cdepso|cvilso|sexsoc|bgesso|aadhso|anaiso|mnaiso|jnaiso|cspsoc|asaiso|msaico|jsaiso|sitmat|nbenf|accmai|accsms|   sitpav1|
+-----+------+------+------+------+------+------+------+------+------+------+------+------+------+-----+------+------+----------+
|    1|    20|   166|     1|    33|  1983|  1936|    12|    18|  NULL|  2017|     1|    19|    NC|    0|     1|     1|Non abonné|
|    3|    78|   420|     1|    90|  1983|  1958|    12|     3|    40|  2017|     1|    19|     O|    0|     0|     0|    Abonné|
|    5|    92|   361|     1|    90|  1983|  1951|     3|    31|  NULL|  2018|     6|    12|    NC|    0|     0|     1|    Abonné|
|    8|    01|   170|     1|    64|  1983|  1953|     6|     3|  NULL|  2017|     1|    19|    NC|    0|     0|     0|Non abonné|
|    9|    77|   260|     1|    92|  1983|  1951|    10|    15|    20|  2017|     1|    19|     O|    0|     0|     1|    Abonné|
+-----+------+------+------+------+------+------+------+------+------+------+------+------+------+-----+------+------+----------+
only showing top 5 rows

In [43]:
df_c_pd=df_c.toPandas()
df_c_pd

,nusoc,cdepso,cvilso,sexsoc,bgesso,aadhso,anaiso,mnaiso,jnaiso,cspsoc,asaiso,msaico,jsaiso,sitmat,nbenf,accmai,accsms,sitpav1
0,1,20,166,1,33,1983,1936,12,18,None,2017,1,19,NC,0,1,1,Non abonné
1,3,78,420,1,90,1983,1958,12,3,40,2017,1,19,O,0,0,0,Abonné
2,5,92,361,1,90,1983,1951,3,31,None,2018,6,12,NC,0,0,1,Abonné
3,8,01,170,1,64,1983,1953,6,3,None,2017,1,19,NC,0,0,0,Non abonné
4,9,77,260,1,92,1983,1951,10,15,20,2017,1,19,O,0,0,1,Abonné
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389393,799992,15,600,1,62,2017,1996,12,4,62,2022,7,31,N,0,1,1,Non abonné
389394,799993,33,420,1,9,2017,1964,5,15,20,2021,10,15,N,0,1,1,Abonné
389395,799995,37,530,1,84,2017,1994,3,22,62,2019,3,28,N,0,1,1,Non abonné
389396,799996,59,790,1,166,2017,1987,7,30,30,2020,4,1,O,0,1,1,Non abonné
389397,799998,52,360,1,131,2017,1965,4,12,80,2017,2,22,NC,0,1,1,Non abonné

Silver CLIENT : calcul de l’âge

In [52]:
from pyspark.sql.functions import col, lit

ANNEE_ETUDE = 2022

df_client_silver = df_c.withColumn(
    "age_client",
    lit(ANNEE_ETUDE) - col("anaiso")
)

In [53]:
df_c_pd=df_client_silver.toPandas()
df_c_pd

,nusoc,cdepso,cvilso,sexsoc,bgesso,aadhso,anaiso,mnaiso,jnaiso,cspsoc,asaiso,msaico,jsaiso,sitmat,nbenf,accmai,accsms,sitpav1,age_client
0,1,20,166,1,33,1983,1936,12,18,None,2017,1,19,NC,0,1,1,Non abonné,86
1,3,78,420,1,90,1983,1958,12,3,40,2017,1,19,O,0,0,0,Abonné,64
2,5,92,361,1,90,1983,1951,3,31,None,2018,6,12,NC,0,0,1,Abonné,71
3,8,01,170,1,64,1983,1953,6,3,None,2017,1,19,NC,0,0,0,Non abonné,69
4,9,77,260,1,92,1983,1951,10,15,20,2017,1,19,O,0,0,1,Abonné,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389393,799992,15,600,1,62,2017,1996,12,4,62,2022,7,31,N,0,1,1,Non abonné,26
389394,799993,33,420,1,9,2017,1964,5,15,20,2021,10,15,N,0,1,1,Abonné,58
389395,799995,37,530,1,84,2017,1994,3,22,62,2019,3,28,N,0,1,1,Non abonné,28
389396,799996,59,790,1,166,2017,1987,7,30,30,2020,4,1,O,0,1,1,Non abonné,35
389397,799998,52,360,1,131,2017,1965,4,12,80,2017,2,22,NC,0,1,1,Non abonné,57

Étape 2 : contrôle qualité

In [54]:
df_client_silver = df_client_silver.filter(
    (col("age_client") >= 14) &
    (col("age_client") <= 100)
)

In [55]:
df_c_pd=df_client_silver.toPandas()
df_c_pd

,nusoc,cdepso,cvilso,sexsoc,bgesso,aadhso,anaiso,mnaiso,jnaiso,cspsoc,asaiso,msaico,jsaiso,sitmat,nbenf,accmai,accsms,sitpav1,age_client
0,1,20,166,1,33,1983,1936,12,18,None,2017,1,19,NC,0,1,1,Non abonné,86
1,3,78,420,1,90,1983,1958,12,3,40,2017,1,19,O,0,0,0,Abonné,64
2,5,92,361,1,90,1983,1951,3,31,None,2018,6,12,NC,0,0,1,Abonné,71
3,8,01,170,1,64,1983,1953,6,3,None,2017,1,19,NC,0,0,0,Non abonné,69
4,9,77,260,1,92,1983,1951,10,15,20,2017,1,19,O,0,0,1,Abonné,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389389,799992,15,600,1,62,2017,1996,12,4,62,2022,7,31,N,0,1,1,Non abonné,26
389390,799993,33,420,1,9,2017,1964,5,15,20,2021,10,15,N,0,1,1,Abonné,58
389391,799995,37,530,1,84,2017,1994,3,22,62,2019,3,28,N,0,1,1,Non abonné,28
389392,799996,59,790,1,166,2017,1987,7,30,30,2020,4,1,O,0,1,1,Non abonné,35
389393,799998,52,360,1,131,2017,1965,4,12,80,2017,2,22,NC,0,1,1,Non abonné,57

Étape 3 : flag “jeune < 30”

In [56]:
from pyspark.sql.functions import when

df_client_silver = df_client_silver.withColumn(
    "client_jeune",
    when(col("age_client") < 30, 1).otherwise(0)
)

In [57]:
df_c_pd=df_client_silver.toPandas()
df_c_pd

,nusoc,cdepso,cvilso,sexsoc,bgesso,aadhso,anaiso,mnaiso,jnaiso,cspsoc,asaiso,msaico,jsaiso,sitmat,nbenf,accmai,accsms,sitpav1,age_client,client_jeune
0,1,20,166,1,33,1983,1936,12,18,None,2017,1,19,NC,0,1,1,Non abonné,86,0
1,3,78,420,1,90,1983,1958,12,3,40,2017,1,19,O,0,0,0,Abonné,64,0
2,5,92,361,1,90,1983,1951,3,31,None,2018,6,12,NC,0,0,1,Abonné,71,0
3,8,01,170,1,64,1983,1953,6,3,None,2017,1,19,NC,0,0,0,Non abonné,69,0
4,9,77,260,1,92,1983,1951,10,15,20,2017,1,19,O,0,0,1,Abonné,71,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389389,799992,15,600,1,62,2017,1996,12,4,62,2022,7,31,N,0,1,1,Non abonné,26,1
389390,799993,33,420,1,9,2017,1964,5,15,20,2021,10,15,N,0,1,1,Abonné,58,0
389391,799995,37,530,1,84,2017,1994,3,22,62,2019,3,28,N,0,1,1,Non abonné,28,1
389392,799996,59,790,1,166,2017,1987,7,30,30,2020,4,1,O,0,1,1,Non abonné,35,0
389393,799998,52,360,1,131,2017,1965,4,12,80,2017,2,22,NC,0,1,1,Non abonné,57,0

In [58]:
#Nombre de jeunes 
df_client_silver.groupby("client_jeune").count().show()

+------------+------+
|client_jeune| count|
+------------+------+
|           1|  9459|
|           0|379935|
+------------+------+

5- Jointure CLIENT ↔ CONTRAT (Silver)

In [61]:
df_silver_global = df_silver.join(
    df_client_silver.select(
        "nusoc", "age_client", "client_jeune", "sexsoc",
        "cspsoc", "sitmat", "sitpav1"
    ),
    on="nusoc",
    how="inner"
)

In [62]:
df_s_join_pd=df_silver_global.toPandas()
df_s_join_pd

,nusoc,nucon,cateco,g01co,g02co,g03co,g04co,g05co,g06co,g09co,...,etat_contrat_libelle,usage_vehicule,nb_garanties,anciennete_contrat,age_client,client_jeune,sexsoc,cspsoc,sitmat,sitpav1
0,3,1,M,1,1,1,1,1,1,1,...,Résilié sociétaire,Domicile-Travail,10,19,64,0,1,40,O,Abonné
1,15,14,M,1,1,1,1,1,1,1,...,En cours,Domicile-Travail,11,4,74,0,1,61,O,Abonné
2,15,15,M,1,1,1,1,1,1,1,...,En cours,Domicile-Travail,11,4,74,0,1,61,O,Abonné
3,16,3,A,1,1,1,1,1,1,1,...,En cours,Domicile-Travail,10,4,65,0,1,12,O,Abonné
4,18,1,M,1,1,1,1,1,1,1,...,Annulé,Domicile-Travail,11,13,71,0,1,80,NC,Non abonné
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170608,421533,1,A,1,1,0,0,0,0,0,...,Résilié sociétaire,Domicile-Travail,4,12,40,0,1,40,N,Non abonné
170609,421538,1,M,1,1,0,0,0,0,0,...,Résilié sociétaire,Domicile-Travail,6,9,43,0,1,40,NC,Non abonné
170610,421571,1,M,1,1,0,0,0,0,0,...,Résilié impayé,Domicile-Travail,5,10,48,0,1,40,N,Non abonné
170611,421588,4,M,1,1,1,1,1,1,1,...,En cours,Domicile-Travail,11,4,68,0,1,14,O,Non abonné
170612,421608,2,M,1,1,0,0,0,0,0,...,Résilié sociétaire,Domicile-Travail,5,5,51,0,1,30,N,Non abonné

4- Indicateurs Silver pour ANALYSER les jeunes

In [67]:
#Profil des jeunes
df_silver_global = df_silver_global.withColumn(
    "jeune_moto",
    when((col("client_jeune") == 1) & (col("cateco") == "M"), 1).otherwise(0)
)